-- UNIFIED SCHEMA SCRIPT
-- Run this in Supabase SQL Editor to standardize your tables and fix type mismatches.
--add this schema t the supabase

-- 1. USERS TABLE (Source of Truth for User IDs = BigInt)add usrrs (s)
CREATE TABLE IF NOT EXISTS public.user (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  email text unique not null,
  name text,
  password text,
  avatar text,
  is_verified boolean default false,
  verification_token text
);

-- 2. RESTAURANTS TABLE (Source of Truth for Restaurant IDs = UUID)
-- Matches your latest structure including latitude/longitude and menu.
CREATE TABLE IF NOT EXISTS public.restaurants (
  id uuid default gen_random_uuid() primary key,
  owner_id bigint references public.users(id), -- Matches users.id (BigInt)
  name text not null,
  cuisine text,
  price text,
  location text,
  description text,
  images text[],
  active_days text[],
  opening_time text,
  closing_time text,
  tags text[],
  menu jsonb,
  latitude double precision,
  longitude double precision,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. BOOKINGS TABLE (The Critical Fix)
-- This table was failing because it mixed up BigInt and UUID types.
-- We DROP and RECREATE it to ensure it perfectly matches the other two tables.

DROP TABLE IF EXISTS public.bookings;

CREATE TABLE public.bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- CORRECT: References users.id which is BIGINT
  user_id bigint references public.users(id) not null,
  
  -- CORRECT: References restaurants.id which is UUID
  restaurant_id uuid references public.restaurants(id) not null,
  
  restaurant_name text,
  date text not null,
  time text not null,
  party_size int not null,
  
  -- The new column needed for receipts
  booking_code text,
  
  -- Sataus for cancellations
  status text default 'confirmed'
);

-- 4. REVIEWS TABLE (Consistent Types)
-- Ensures reviews also link correctly to UUID restaurants and BigInt users.
CREATE TABLE IF NOT EXISTS public.reviews (
  id uuid default gen_random_uuid() primary key,
  
  -- CORRECT: References restaurants.id (UUID)
  restaurant_id uuid references public.restaurants(id) not null,
  
  -- CORRECT: References users.id (BigInt)
  user_id bigint references public.users(id),
  
  user_name text not null,
  rating integer check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. ENABLE ROW LEVEL SECURITY (Optional/Safe Defaults)
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for now" ON public.bookings FOR ALL USING (true);
