-- UNIFIED SCHEMA SCRIPT
-- Run this in Supabase SQL Editor to standardize your tables and fix type mismatches.
--add this schema t the supabase

-- 1. USERS TABLE (Source of Truth for User IDs = BigInt)add usrrs (s)
CREATE TABLE IF NOT EXISTS public.user (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  email text unique not null,
  name text,
  password text,
  avatar text,
  is_verified boolean default false,
  verification_token text,
  loyalty_points bigint default 0
);

-- 2. RESTAURANTS TABLE (Source of Truth for Restaurant IDs = UUID)
-- Matches your latest structure including latitude/longitude and menu.
CREATE TABLE IF NOT EXISTS public.restaurants (
  id uuid default gen_random_uuid() primary key,
  owner_id bigint references public.users(id), -- Matches users.id (BigInt)
  name text not null,
  cuisine text,
  city text,
  price text,
  location text,
  description text,
  images text[],
  active_days text[],
  opening_time text,
  closing_time text,
  tags text[],
  menu jsonb,
  latitude double precision,
  longitude double precision,
  phone_number text,
  website_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. BOOKINGS TABLE (The Critical Fix)
-- This table was failing because it mixed up BigInt and UUID types.
-- We DROP and RECREATE it to ensure it perfectly matches the other two tables.

DROP TABLE IF EXISTS public.bookings;

CREATE TABLE public.bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- CORRECT: References users.id which is BIGINT
  user_id bigint references public.users(id) not null,
  
  -- CORRECT: References restaurants.id which is UUID
  restaurant_id uuid references public.restaurants(id) not null,
  
  restaurant_name text,
  date text not null,
  time text not null,
  party_size int not null,
  
  -- The new column needed for receipts
  booking_code text,
  
  -- Sataus for cancellations
  status text default 'confirmed'
);

-- 4. REVIEWS TABLE (Consistent Types)
-- Ensures reviews also link correctly to UUID restaurants and BigInt users.
CREATE TABLE IF NOT EXISTS public.reviews (
  id uuid default gen_random_uuid() primary key,
  
  -- CORRECT: References restaurants.id (UUID)
  restaurant_id uuid references public.restaurants(id) not null,
  
  -- CORRECT: References users.id (BigInt)
  user_id bigint references public.users(id),
  
  user_name text not null,
  rating integer check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. WEB REVIEWS TABLE (Site-wide user reviews, not restaurant-specific)
CREATE TABLE IF NOT EXISTS public.web_reviews (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) not null,
  user_name text not null,
  user_avatar text,
  rating integer check (rating >= 1 and rating <= 5) not null,
  comment text not null,
  is_approved boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. BANNER ADS TABLE (Dynamic ad banners managed by super admin)
CREATE TABLE IF NOT EXISTS public.banner_ads (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text not null,
  link_url text,
  is_active boolean default true,
  impressions bigint default 0,
  clicks bigint default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. PAYMENTS TABLE (Restaurant payment submissions for admin approval)
CREATE TABLE IF NOT EXISTS public.payments (
  id bigint generated by default as identity primary key,
  restaurant_id uuid references public.restaurants(id) on delete cascade,
  restaurant_name text,
  user_id bigint references public.users(id) on delete set null,
  sender_name text not null,
  account_type text not null,
  screenshot_url text,
  status text default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8. ENABLE ROW LEVEL SECURITY (Optional/Safe Defaults)

-- 8a. BLOGS TABLE (SEO-friendly blog posts managed by super admin)
CREATE TABLE IF NOT EXISTS public.blogs (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  excerpt text,
  content text not null,
  cover_image text,
  author_name text not null default 'ReserveKaru Team',
  tags text[],
  is_published boolean default false,
  published_at timestamp with time zone,
  meta_title text,
  meta_description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8b. BLOGS RLS
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for blogs" ON public.blogs FOR ALL USING (true);

-- 9. ENABLE ROW LEVEL SECURITY (Optional/Safe Defaults)
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for now" ON public.bookings FOR ALL USING (true);
ALTER TABLE public.web_reviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for web_reviews" ON public.web_reviews FOR ALL USING (true);
ALTER TABLE public.banner_ads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for banner_ads" ON public.banner_ads FOR ALL USING (true);
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for payments" ON public.payments FOR ALL USING (true);
