
import { useState } from 'react';
import { X, Star } from 'lucide-react';
import { supabase } from '../supabase';
import { useAuth } from '../context/AuthContext';

export default function ReviewModal({ isOpen, onClose, restaurantId, onReviewSubmitted }) {
    const { user } = useAuth();
    const [rating, setRating] = useState(5);
    const [text, setText] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');

    if (!isOpen) return null;

    const handleSubmit = async (e) => {
        e.preventDefault();
        setLoading(true);
        setError('');

        if (!user) {
            setError('You must be logged in to review.');
            setLoading(false);
            return;
        }

        if (!text.trim()) {
            setError('Please write a review.');
            setLoading(false);
            return;
        }

        try {
            const { error: dbError } = await supabase
                .from('reviews')
                .insert([
                    {
                        restaurant_id: restaurantId,
                        user_name: user.name,
                        rating: rating,
                        comment: text,
                        user_id: user.id,
                        created_at: new Date().toISOString() // Optional, usually auto-generated by DB
                    }
                ]);

            if (dbError) throw dbError;

            onReviewSubmitted();
            onClose();
            setText('');
            setRating(5);
        } catch (err) {
            // eslint-disable-next-line no-console
            console.error('Submission error:', err);
            setError(err.message || 'Failed to submit review.');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div style={{
            position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
            background: 'rgba(0,0,0,0.7)', backdropFilter: 'blur(5px)',
            display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000
        }} onClick={onClose}>
            <div className="glass" style={{
                width: '100%', maxWidth: '500px', padding: '2rem', borderRadius: '16px',
                position: 'relative', border: '1px solid rgba(255, 255, 255, 0.1)'
            }} onClick={e => e.stopPropagation()}>

                <button
                    onClick={onClose}
                    style={{
                        position: 'absolute', top: '1.5rem', right: '1.5rem',
                        background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer'
                    }}
                >
                    <X size={24} />
                </button>

                <h2 style={{ fontSize: '1.5rem', marginBottom: '1.5rem', fontWeight: 600 }}>Write a Review</h2>

                <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>

                    {/* Rating Section */}
                    <div>
                        <label style={{ display: 'block', marginBottom: '0.5rem', color: 'var(--text-muted)' }}>Rating</label>
                        <div style={{ display: 'flex', gap: '8px' }}>
                            {[1, 2, 3, 4, 5].map((star) => (
                                <button
                                    key={star}
                                    type="button"
                                    onClick={() => setRating(star)}
                                    style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0 }}
                                >
                                    <Star
                                        size={32}
                                        fill={star <= rating ? "#fbbf24" : "none"}
                                        color={star <= rating ? "#fbbf24" : "#4b5563"}
                                    />
                                </button>
                            ))}
                        </div>
                    </div>



                    {/* Review Text */}
                    <div>
                        <label style={{ display: 'block', marginBottom: '0.5rem', color: 'var(--text-muted)' }}>Review</label>
                        <textarea
                            value={text}
                            onChange={(e) => setText(e.target.value)}
                            placeholder="Share your experience..."
                            rows={4}
                            style={{
                                width: '100%', padding: '0.75rem', borderRadius: '8px',
                                background: 'rgba(255,255,255,0.05)', border: '1px solid var(--glass-border)',
                                color: 'white', fontFamily: 'inherit', resize: 'vertical'
                            }}
                        />
                    </div>

                    {error && <p style={{ color: '#ef4444', fontSize: '0.9rem' }}>{error}</p>}

                    <div style={{ display: 'flex', gap: '1rem', marginTop: '0.5rem' }}>
                        <button
                            type="button"
                            onClick={onClose}
                            className="btn"
                            style={{ flex: 1, background: 'rgba(255,255,255,0.1)' }}
                        >
                            Cancel
                        </button>
                        <button
                            type="submit"
                            className="btn btn-primary"
                            style={{ flex: 1 }}
                            disabled={loading}
                        >
                            {loading ? 'Submitting...' : 'Submit Review'}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
}
